name: Validate Complexities

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  changedFiles:
    runs-on: ubuntu-latest
    name: check-changed-files
    permissions:
      pull-requests: read

    steps:
      # Step to checkout the repository
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v45

      - name: Check Files for Time or Space Complexities
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
          REPO_NAME: ${{ github.repository }}
          GITHUB_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            # Only check files with .java or .py extensions
            if [[ "$file" == *.java || "$file" == *.py ]]; then
              # Construct the raw URL for each file
              raw_url="https://raw.githubusercontent.com/${REPO_NAME}/${GITHUB_SHA}/${file}"
              
              echo "Checking $raw_url for complexity annotations..."
              
              # Fetch the file content without authentication
              content=$(curl -s "$raw_url")
              
              # Set flags for found keywords
              has_time=false
              has_space=false
              while IFS= read -r line; do
                # Check for time complexity annotation
                if echo "$line" | grep -iq "time complexity"; then
                  has_time=true
                fi
                
                # Check for space complexity annotation
                if echo "$line" | grep -iq "space complexity"; then
                  has_space=true
                fi

                # If both are found, no need to check further
                if $has_time && $has_space; then
                  break
                fi
              done <<< "$content"
              
              # Check if both flags are set to true
              if $has_time && $has_space; then
                echo "✅ $file has the necessary time/space complexities."
              else
                echo "❌ $file is missing either time or space complexity."
                exit 1
              fi
            else
              echo "Skipping $file as it is not a .java or .py file."
            fi
          done