name: Validate Pull Request Title and Label

on:
  pull_request:
    types: [opened, edited, labeled]

jobs:
  check-title-and-label:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Pull Request Title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          # Regular expression to match "Day <No.> - <name-solution>"
          if [[ ! "$PR_TITLE" =~ ^Day[[:space:]]+[0-9]+[[:space:]]+-[[:space:]]+[a-zA-Z0-9_-]+$ ]]; then
            echo "❌ Pull request title does not follow the naming convention: 'Day <No.> - name-solution'."
            exit 1
          else
            echo "✅ Pull request title follows the naming convention."
          fi

      - name: Check for Required Label
        env:
          PR_LABELS: ${{ toJSON(github.event.pull_request.labels) }}
        run: |
          # Check if the label "java-solution" or "python-solution" exists
          if [[ "$PR_LABELS" == *'"java-solution"'* ]] || [[ "$PR_LABELS" == *'"python-solution"'* ]]; then
            echo "✅ Required label (java-solution or python-solution) is present."
          else
            echo "❌ Pull request must have either the 'java-solution' or 'python-solution' label."
            exit 1
          fi